<?php

namespace ContainerTeJBs6J;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_8J6GEchService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.8J6GEch' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.8J6GEch'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Controller\\EventController::index' => ['privates', '.service_locator.Lnv_epI.App\\Controller\\EventController::index()', 'getEventControllerindexService', true],
            'App\\Controller\\RoomController::index' => ['privates', '.service_locator.P.blNFL.App\\Controller\\RoomController::index()', 'getRoomControllerindexService', true],
            'App\\Controller\\RoomController::show' => ['privates', '.service_locator.P.blNFL.App\\Controller\\RoomController::show()', 'getRoomControllershowService', true],
            'App\\Controller\\UserController::index' => ['privates', '.service_locator.P.blNFL.App\\Controller\\UserController::index()', 'getUserControllerindexService', true],
            'App\\Controller\\UserController::show' => ['privates', '.service_locator.P.blNFL.App\\Controller\\UserController::show()', 'getUserControllershowService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Controller\\EventController:index' => ['privates', '.service_locator.Lnv_epI.App\\Controller\\EventController::index()', 'getEventControllerindexService', true],
            'App\\Controller\\RoomController:index' => ['privates', '.service_locator.P.blNFL.App\\Controller\\RoomController::index()', 'getRoomControllerindexService', true],
            'App\\Controller\\RoomController:show' => ['privates', '.service_locator.P.blNFL.App\\Controller\\RoomController::show()', 'getRoomControllershowService', true],
            'App\\Controller\\UserController:index' => ['privates', '.service_locator.P.blNFL.App\\Controller\\UserController::index()', 'getUserControllerindexService', true],
            'App\\Controller\\UserController:show' => ['privates', '.service_locator.P.blNFL.App\\Controller\\UserController::show()', 'getUserControllershowService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\EventController::index' => '?',
            'App\\Controller\\RoomController::index' => '?',
            'App\\Controller\\RoomController::show' => '?',
            'App\\Controller\\UserController::index' => '?',
            'App\\Controller\\UserController::show' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\EventController:index' => '?',
            'App\\Controller\\RoomController:index' => '?',
            'App\\Controller\\RoomController:show' => '?',
            'App\\Controller\\UserController:index' => '?',
            'App\\Controller\\UserController:show' => '?',
        ]);
    }
}
