<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTeJBs6J\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTeJBs6J/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTeJBs6J.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTeJBs6J\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTeJBs6J\App_KernelDevDebugContainer([
    'container.build_hash' => 'TeJBs6J',
    'container.build_id' => '66e4226d',
    'container.build_time' => 1727250002,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTeJBs6J');
